added some error handling

diff --git a/shrug-add b/shrug-add
--- a/shrug-add
+++ b/shrug-add
@@ -1,12 +1,13 @@
 #!/bin/dash
 
-if [ $# -eq 0 ]
+# Check if .shrug exists
+if [ ! -d ".shrug" ]
+then
+    echo "$0: error: no .shrug directory containing shrug repository exists" >> /dev/stderr
+    exit 1;
+elif [ $# -eq 0 ]
 then
     echo "usage: shrug-add <filenames>"
-    exit
-elif [ ! -d ".shrug" ]
-then
-    echo "$0: error: no .shrug directory containing shrug repository exists"
     exit
 fi
 
@@ -22,16 +23,16 @@ do      #Start with not [-./] follow by more than 1 char : Optional : (.)
             fi
             cp $1 ".shrug/index/"
         else                                                    # File not Exists
-            echo "$0: error: can not open '$1'"
-            exit
+            echo "$0: error: can not open '$1'" >> /dev/stderr
+            exit 1
         fi
-    elif echo $1 | egrep "^(-)+[A-Za-z]*" > /dev/null              # Flag Specified
+    elif echo $1 | egrep "^(-)+[A-Za-z]*" > /dev/null           # Flag Specified
     then
         echo "usage: shrug-add <filenames>"
         exit
     else
-        echo "$0: error: invalid filename '$1'"                 # Other Cases (Invalid filename)
-        exit
+        echo "$0: error: invalid filename '$1'" >> /dev/stderr  # Other Cases (Invalid filename)
+        exit 1
     fi
     shift
 done
diff --git a/shrug-cmp b/shrug-cmp
--- a/shrug-cmp
+++ b/shrug-cmp
@@ -3,15 +3,23 @@
 IFS="
 "
 
+# Error checking
+# Check if .shrug exists
+if [ ! -d ".shrug" ]
+then
+    echo "$0: error: no .shrug directory containing shrug repository exists" >> /dev/stderr
+    exit 1;
+fi
+
 if [ $# -ne 2 ]
 then
-    echo "Invalid Argument" >> /dev/stderr
+    echo "Invalid Argument" >> /dev/stderr; exit 1;
 elif [ ! -d $1 ]
 then
-    echo "$0: error: directory '$1' do not exist" >> /dev/stderr
+    echo "$0: error: directory '$1' do not exist" >> /dev/stderr; exit 1;
 elif [ ! -d $2 ]
 then
-    echo "$0: error: directory '$2' do not exist" >> /dev/stderr
+    echo "$0: error: directory '$2' do not exist" >> /dev/stderr; exit 1;
 else
     out=`diff -q $1 $2`     # Support for subdirectory -r
     for line in $out; do
diff --git a/shrug-commit b/shrug-commit
--- a/shrug-commit
+++ b/shrug-commit
@@ -2,6 +2,7 @@
 
 IFS="
 "
+
 # Constants
 commit_dir=".shrug/commit"
 index_dir=".shrug/index"
@@ -10,14 +11,21 @@ shrug_cmp="shrug-cmp"
 usage="usage: shrug-commit [-a] -m commit-message"
 
 a_flag=0
-# Check shrug repo exist
 
+# Check if .shrug exists
+if [ -d ".shrug" ]
+then
+    echo "$0: error: no .shrug directory containing shrug repository exists" >> /dev/stderr
+    exit 1;
+fi
 
-if [ $# -lt 2 ]         # Check argument number
+# Check argument number
+if [ $# -lt 2 ]
 then
     echo $usage
-    exit
-else                    # Process argument
+    exit 
+# Process Arguments
+else
     while [ $1 ]
     do 
         if echo $1 | egrep "^-m$" > /dev/null && echo $2 | egrep -v "^-.+" > /dev/null
diff --git a/shrug-show b/shrug-show
--- a/shrug-show
+++ b/shrug-show
@@ -1,39 +1,54 @@
 #!/bin/dash
 
+# Constants
 usage="usage: shrug-show <commit>:<filename>"
+commit_dir=".shrug/commit"
+index_dir=".shrug/index"
+log_file=".shrug/log"
 
-if echo $1 | egrep ":" > /dev/null
-then
+# Check if .shrug exists
+if [ ! -d ".shrug" ]; then
+    echo "$0: error: no .shrug directory containing shrug repository exists" >> /dev/stderr
+    exit 1;
+elif [ ! -d $log_file ]; then
+    echo "$0: error: your repository does not have any commits yet" >> /dev/stderr
+    exit 1;
+fi
+
+# Check if argument is in the right format 
+if echo $1 | egrep ":" > /dev/null; then    
     commit=`echo $1 | cut -d ":" -f1`
     file=`echo $1 | cut -d ":" -f2`
+
     # Check filename
-    if echo $file | egrep "^[\.-]" > /dev/null || echo $file | egrep -v "^[A-Za-z\.0-9-]+$" > /dev/null
-    then
-        echo "$0: error: invalid filename '$file'"
-        exit
-    fi
-    # Check commit -> default to index
-    if [ ! $commit ]
-    then
-        if [ -f ".shrug/index/$file" ]
+    if echo $file | egrep "^[\.-]" > /dev/null \
+        || echo $file | egrep -v "^[A-Za-z\.0-9-]+$" > /dev/null;
         then
-            cat ".shrug/index/$file"
+        echo "$0: error: invalid filename '$file'" >> /dev/stderr
+        exit 1;
+    fi
+    
+    # Check if commit argument is given
+    if [ ! $commit ]; then
+        # Check file under index exist
+        if [ -f "$index_dir/$file" ]; then
+            cat "$index_dir/$file"
         else
-            echo "$0: error: '$file' not found in index"
+            echo "$0: error: '$file' not found in index" >> /dev/stderr
+            exit 1
+        fi
+    # Check commit exist
+    elif [ -d "$commit_dir/$commit" ]; then
+        # Check file under commit exist
+        if [ -f "$commit_dir/$commit/$file" ]; then
+            cat "$commit_dir/$commit/$file"
+        else
+            echo "$0: error: '$file' not found in commit $commit" >> /dev/stderr
+            exit 1
         fi
     else
-    # Check commit and file exist
-        if [ -d ".shrug/commit/$commit" ]
-        then
-            if [ -f ".shrug/commit/$commit/$file" ]
-            then
-                cat ".shrug/commit/$commit/$file"
-            else
-                echo "$0: error: '$file' not found in commit $commit"
-            fi
-        else
-            echo "$0: error: unknown commit '$commit'"
-        fi
+        echo "$0: error: unknown commit '$commit'" >> /dev/stderr
+        exit 1
     fi
 else
     echo $usage
