limit 80 characters per line

diff --git a/shrug-cmp b/shrug-cmp
--- a/shrug-cmp
+++ b/shrug-cmp
@@ -5,34 +5,34 @@ IFS="
 
 # Error checking
 # Check if .shrug exists
-if [ ! -d ".shrug" ]
-then
-    echo "$0: error: no .shrug directory containing shrug repository exists" >> /dev/stderr
-    exit 1;
+if [ ! -d ".shrug" ]; then
+    echo "$0: error: no .shrug directory containing shrug repository exists" \
+        >>/dev/stderr
+    exit 1
 fi
 
-if [ $# -ne 2 ]
-then
-    echo "Invalid Argument" >> /dev/stderr; exit 1;
-elif [ ! -d $1 ]
-then
-    echo "$0: error: directory '$1' do not exist" >> /dev/stderr; exit 1;
-elif [ ! -d $2 ]
-then
-    echo "$0: error: directory '$2' do not exist" >> /dev/stderr; exit 1;
+if [ $# -ne 2 ]; then
+    echo "Invalid Argument" >>/dev/stderr
+    exit 1
+elif [ ! -d $1 ]; then
+    echo "$0: error: directory '$1' do not exist" >>/dev/stderr
+    exit 1
+elif [ ! -d $2 ]; then
+    echo "$0: error: directory '$2' do not exist" >>/dev/stderr
+    exit 1
 else
-    out=`diff -q $1 $2`     # Support for subdirectory -r
+    out=$(diff -q $1 $2) # Support for subdirectory -r
     for line in $out; do
-        if echo "$line" | egrep "Files (.*) and (.*) differ" > /dev/null; then
+        if echo "$line" | egrep "Files (.*) and (.*) differ" >/dev/null; then
             # File changed
-            file=`echo $line | cut -d " " -f2 | rev | cut -d "/" -f1 | rev`
+            file=$(echo $line | cut -d " " -f2 | rev | cut -d "/" -f1 | rev)
             echo "~ $file"
             continue
-        elif echo "$line" | egrep "Only in (.*): " > /dev/null; then
+        elif echo "$line" | egrep "Only in (.*): " >/dev/null; then
             # File added / removed
-            directory=`echo $line | cut -d " " -f3`
-            file=`echo $line | cut -d " " -f4`
-            if echo "$directory" | egrep "$1" > /dev/null; then
+            directory=$(echo $line | cut -d " " -f3)
+            file=$(echo $line | cut -d " " -f4)
+            if echo "$directory" | egrep "$1" >/dev/null; then
                 # File exist in directory $1 only
                 echo "+ $file"
             else
diff --git a/shrug-commit b/shrug-commit
--- a/shrug-commit
+++ b/shrug-commit
@@ -12,32 +12,28 @@ shrug_add="shrug-add"
 usage="usage: shrug-commit [-a] -m commit-message"
 
 # Check if .shrug exists
-if [ ! -d ".shrug" ]
-then
-    echo "$0: error: no .shrug directory containing shrug repository exists" >> /dev/stderr
-    exit 1;
+if [ ! -d ".shrug" ]; then
+    echo "$0: error: no .shrug directory containing\ shrug repository exists" \
+        >>/dev/stderr
+    exit 1
 fi
 
 # Check argument number
-if [ $# -lt 2 ]
-then
+if [ $# -lt 2 ]; then
     echo $usage
-    exit 
+    exit
 # Process Arguments
 else
-    while [ $1 ]
-    do 
-        if echo $1 | egrep "^-m$" > /dev/null && echo $2 | egrep -v "^-.+" > /dev/null
-        then
+    while [ $1 ]; do
+        if echo $1 | egrep "^-m$" >/dev/null \
+            && echo $2 | egrep -v "^-.+" >/dev/null; then
             msg=$2
             shift
-        elif echo $1 | egrep "^-a$" > /dev/null
-        then
-            for file in `find $index_dir -type f`
-            do
-                filename=`echo $file | rev | cut -d "/" -f1 | rev`
+        elif echo $1 | egrep "^-a$" >/dev/null; then
+            for file in $(find $index_dir -type f); do
+                filename=$(echo $file | rev | cut -d "/" -f1 | rev)
                 # echo "$filename"
-                `$shrug_add $filename`
+                $($shrug_add $filename)
                 # echo "update $file"
             done
         else
@@ -50,32 +46,29 @@ fi
 
 # Check if repo has previous commit
 commit_no=0
-if [ ! -d $commit_dir ]
-then
+if [ ! -d $commit_dir ]; then
     mkdir "$commit_dir"
 else
-    commit_no=`cat $log_file | tail -1 | cut -d " " -f1`
-    commit_no=$(($commit_no+1))
+    commit_no=$(cat $log_file | tail -1 | cut -d " " -f1)
+    commit_no=$(($commit_no + 1))
 fi
 
 # echo "$commit_no $msg" >> ".shrug/log.txt"
-if [ $commit_no -ne 0 ]; then           # Not initial commit
-    differ=` $shrug_cmp "$index_dir" "$commit_dir/$(($commit_no-1))" `
-    if [ -n "$differ" ]
-    then
-        for line in $differ
-        do
-            file=` echo $line | cut -d " " -f2 `
+if [ $commit_no -ne 0 ]; then # Not initial commit
+    differ=$($shrug_cmp "$index_dir" "$commit_dir/$(($commit_no - 1))")
+    if [ -n "$differ" ]; then
+        for line in $differ; do
+            file=$(echo $line | cut -d " " -f2)
         done
         cp -r "$index_dir/." "$commit_dir/$commit_no"
-        echo "$commit_no $msg" >> "$log_file"
+        echo "$commit_no $msg" >>"$log_file"
         echo "Committed as commit $commit_no"
     else
         echo "nothing to commit"
     fi
-else                            # Initial commit
+else # Initial commit
     cp -r "$index_dir/." "$commit_dir/$commit_no"
-    echo "$commit_no $msg" >> "$log_file"
+    echo "$commit_no $msg" >>"$log_file"
     echo "Committed as commit $commit_no"
 fi
 
diff --git a/shrug-rm b/shrug-rm
--- a/shrug-rm
+++ b/shrug-rm
@@ -7,111 +7,99 @@ force_flag=0
 cached_flag=0
 log_file=".shrug/log"
 
-
 commit_no=""
-if [ -d .shrug/commit ]
-then
-    commit_no=`cat $log_file | tail -1 | cut -d " " -f1`
+if [ -d .shrug/commit ]; then
+    commit_no=$(cat $log_file | tail -1 | cut -d " " -f1)
 fi
 
-
 # Check if .shrug exists
-if [ ! -d ".shrug" ]
-then
-    echo "$0: error: no .shrug directory containing shrug repository exists" >> /dev/stderr
-    exit 1;
+if [ ! -d ".shrug" ]; then
+    echo "$0: error: no .shrug directory containing \
+            shrug repository exists" >>/dev/stderr
+    exit 1
 fi
 
 files=""
 
 # Check argument number
-if [ $# -lt 1 ]
-then
+if [ $# -lt 1 ]; then
     echo "$usage"
-    exit 
+    exit
 # Process Flags
 else
-    for argv in $@
-    do
-        if echo $argv | egrep "^--force$" > /dev/null
-        then
+    for argv in $@; do
+        if echo $argv | egrep "^--force$" >/dev/null; then
             force_flag=1
-        elif echo $argv | egrep "^--cached$" > /dev/null
-        then
+        elif echo $argv | egrep "^--cached$" >/dev/null; then
             cached_flag=1
-        elif echo $argv | egrep "^-" > /dev/null
-        then
+        elif echo $argv | egrep "^-" >/dev/null; then
             echo "$usage"
             exit
-        elif [ -n "$files" ]
-        then
-            files=` echo "$files $argv" `
-        else 
+        elif [ -n "$files" ]; then
+            files=$(echo "$files $argv")
+        else
             files="$argv"
         fi
     done
 fi
 
-if [ -z "$files" ]
-then
+if [ -z "$files" ]; then
     echo "$usage"
     exit
 fi
 
-for file in $files
-do
+for file in $files; do
     # check if file exists in index
-    if [ -f ".shrug/index/$file" ]
-    then
+    if [ -f ".shrug/index/$file" ]; then
         # Check if file inside index is different from file in directory
         # Check if file inside index is different from last commit
         # No commit
-        if [ -z $commit_no ]
-        then 
-            echo "$0: error: your repository does not have any commits yet" >> /dev/stderr
-            exit 1;
+        if [ -z $commit_no ]; then
+            echo "$0: error: your repository does not \
+                    have any commits yet" >>/dev/stderr
+            exit 1
         # cached & force
-        elif [ $force_flag -eq 0 ] && [ $cached_flag -eq 0 ]
-        then
+        elif [ $force_flag -eq 0 ] && [ $cached_flag -eq 0 ]; then
             # working dir != index
-            if $(`shrug-diff .shrug/index/$file $file`)
-            then
-                if [ -f .shrug/commit/$commit_no/$file ] \
-                    && $(`shrug-diff ".shrug/index/$file" ".shrug/commit/$commit_no/$file"`)
-                then
-                    echo "$0: error: '$file' in index is different to both working file and repository" >> /dev/stderr
+            if shrug-diff .shrug/index/$file $file; then
+                if [ -f .shrug/commit/$commit_no/$file ] &&
+                    shrug-diff ".shrug/index/$file" \
+                               ".shrug/commit/$commit_no/$file"; then
+                    echo "$0: error: '$file' in index is different to both \
+                            working file and repository" >>/dev/stderr
                     exit 1
                 else
-                    echo "$0: error: '$file' in repository is different to working file" >> /dev/stderr
+                    echo "$0: error: '$file' in repository is \
+                            different to working file" >>/dev/stderr
                     exit 1
                 fi
             # index != commit
-            elif $(`shrug-diff .shrug/index/$file .shrug/commit/$commit_no/$file`)
-            then
-                echo "$0: error: '$file' has changes staged in the index" >> /dev/stderr
+            elif shrug-diff .shrug/index/$file \
+                .shrug/commit/$commit_no/$file; then
+                echo "$0: error: '$file' has changes staged in the index" 
+                    >>/dev/stderr
                 exit 1
             fi
         # cached & ! force
-        elif [ $cached_flag -eq 1 ] && [ $force_flag -eq 0 ]
-        then
+        elif [ $cached_flag -eq 1 ] && [ $force_flag -eq 0 ]; then
             # working dir != index != commit
-            if $(`shrug-diff .shrug/index/$file $file`) \
-                && [ -f .shrug/commit/$commit_no/$file ] \
-                && $(`shrug-diff ".shrug/index/$file" ".shrug/commit/$commit_no/$file"`)
-            then
-                echo "$0: error: '$file' in index is different to both working file and repository" >> /dev/stderr
+            if shrug-diff .shrug/index/$file $file &&
+                [ -f .shrug/commit/$commit_no/$file ] &&
+                shrug-diff ".shrug/index/$file" \
+                           ".shrug/commit/$commit_no/$file"; then
+                echo "$0: error: '$file' in index is different to 
+                        both working file and repository" >>/dev/stderr
                 exit 1
             fi
         fi
         rm ".shrug/index/$file"
 
         # Remove file on current directory if --cached is not specified
-        if [ $cached_flag -ne 1 ] && [ -f "$file" ]
-        then
+        if [ $cached_flag -ne 1 ] && [ -f "$file" ]; then
             rm "$file"
         fi
     else
-        echo "$0: error: '$file' is not in the shrug repository" >> /dev/stderr
-        exit 1;
+        echo "$0: error: '$file' is not in the shrug repository" >>/dev/stderr
+        exit 1
     fi
 done
